#!/usr/bin/env bun
import { $ } from "bun";
import { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { NETWORKS } from "./networks.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..", "..");
const PACKS_DIR = join(REPO_ROOT, "packs");

const PUBLISHABLE_PACKAGES = ["abi", "deployments"] as const;

type Version = { value: string; isPrerelease: boolean };

type Address = `0x${string}`;

type Network = {
  chainId: number;
  name: string;
  addresses: Record<string, Address>;
};

/**
 * Parses a release tag (e.g. `v1.2.3` or `v1.2.3-beta.0`) into a SemVer string
 * + a prerelease flag. The flag drives the `beta` npm dist-tag.
 */
function parseVersion(raw: string): Version {
  const v = raw.startsWith("v") ? raw.slice(1) : raw;
  return { value: v, isPrerelease: v.includes("-") };
}

/**
 * Resolves the release version from, in priority order: `argv[2]`,
 * `GITHUB_REF_NAME`, `VERSION`. Throws if none are set.
 */
function readVersion(): Version {
  const argv = process.argv.slice(2);
  const fromArg = argv.find((a) => !a.startsWith("--"));
  const raw = fromArg ?? process.env.GITHUB_REF_NAME ?? process.env.VERSION;
  if (!raw) {
    throw new Error(
      "version required: pass as argv[2] or set GITHUB_REF_NAME / VERSION (e.g. 'v1.2.3' or '1.2.3-beta.0')",
    );
  }
  return parseVersion(raw);
}

/**
 * Emits the TS source for a single entry in the generated `networks` object
 * literal. The key is JSON-encoded so kebab-case names (`paseo-previewnet`)
 * are quoted correctly.
 */
function formatNetworkEntry(key: string, network: Network): string {
  const addrLines = Object.entries(network.addresses).map(
    ([name, addr]) => `      ${name}: ${JSON.stringify(addr)},`,
  );
  return [
    `  ${JSON.stringify(key)}: {`,
    `    chainId: ${network.chainId},`,
    `    name: ${JSON.stringify(network.name)},`,
    `    addresses: {`,
    ...addrLines,
    `    },`,
    `  },`,
  ].join("\n");
}

/**
 * Generates the full source of `packages/deployments/src/generated.ts` from
 * the `deployments/<dir>/<chainId>.json` files registered in
 * `scripts/release/networks.ts`. Networks without a deployment file are
 * skipped with a log line; throws if no networks have data at all.
 */
function generateDeploymentsSource(): string {
  const root = join(REPO_ROOT, "deployments");
  const entries: string[] = [];

  for (const [dirName, meta] of Object.entries(NETWORKS)) {
    const dir = join(root, dirName);
    if (!existsSync(dir)) {
      console.log(`[pack] skipping ${meta.key}: deployments/${dirName} does not exist yet`);
      continue;
    }
    const files = readdirSync(dir).filter((f) => f.endsWith(".json"));
    if (files.length === 0) {
      console.log(`[pack] skipping ${meta.key}: no <chainId>.json under deployments/${dirName}`);
      continue;
    }
    if (files.length > 1) {
      throw new Error(
        `expected exactly one <chainId>.json in ${dir}, found ${files.length}: ${files.join(", ")}`,
      );
    }
    const chainIdStr = files[0]!.replace(/\.json$/, "");
    const chainId = Number(chainIdStr);
    if (!Number.isFinite(chainId) || chainId <= 0) {
      throw new Error(`invalid chain id parsed from filename: ${files[0]}`);
    }

    const raw = JSON.parse(readFileSync(join(dir, files[0]!), "utf8")) as Record<string, Address>;
    const addresses = Object.fromEntries(
      Object.entries(raw)
        .filter(([k]) => !k.startsWith("_"))
        .sort(([a], [b]) => a.localeCompare(b)),
    );
    if (Object.keys(addresses).length === 0) {
      console.log(`[pack] skipping ${meta.key}: deployment file has no addresses yet`);
      continue;
    }

    entries.push(formatNetworkEntry(meta.key, { chainId, name: meta.display, addresses }));
  }

  if (entries.length === 0) {
    throw new Error("no deployed networks found; refusing to publish an empty @dotns/deployments");
  }

  return [
    "// AUTO-GENERATED by scripts/release/pack.ts. Do not edit by hand.",
    "",
    "/** 20-byte EVM address in 0x-prefixed hex. */",
    "export type Address = `0x${string}`;",
    "",
    "/** A DotNS deployment on a single network: chain id, display name, and address book. */",
    "export type Network = {",
    "  chainId: number;",
    "  name: string;",
    "  addresses: Record<string, Address>;",
    "};",
    "",
    "/** Every network DotNS targets, keyed by friendly name. */",
    "export const networks = {",
    entries.join("\n"),
    "} as const satisfies Record<string, Network>;",
    "",
    "/** Union of registered network keys. */",
    "export type NetworkName = keyof typeof networks;",
    "",
  ].join("\n");
}

/**
 * Stamps the package's `package.json` with the release version, strips
 * `private: true` (the publish-safety net), and sets the `beta` dist-tag
 * for prereleases.
 */
async function stampVersion(pkgDir: string, version: Version): Promise<void> {
  await $`npm version ${version.value} --no-git-tag-version --allow-same-version`
    .cwd(pkgDir)
    .quiet();

  const pkgPath = join(pkgDir, "package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
  delete pkg.private;
  if (version.isPrerelease) {
    pkg.publishConfig = { ...(pkg.publishConfig ?? {}), tag: "beta" };
  }
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
}

/** Runs the package's `build` script (wagmi generate + tsc). */
async function buildPackage(pkgDir: string): Promise<void> {
  await $`bun run build`.cwd(pkgDir);
}

/** Runs `npm pack` for the package and writes the tarball to `packsDir`. */
async function packPackage(pkgDir: string, packsDir: string): Promise<void> {
  await $`npm pack --pack-destination ${packsDir}`.cwd(pkgDir).quiet();
}

async function main(): Promise<void> {
  const version = readVersion();
  console.log(`[pack] version=${version.value} prerelease=${version.isPrerelease}`);

  console.log("[pack] forge build");
  await $`forge build`.cwd(REPO_ROOT).env({ ...process.env, FOUNDRY_DISABLE_NIGHTLY_WARNING: "1" });

  console.log("[pack] generating @dotns/deployments source");
  const deploymentsSource = generateDeploymentsSource();
  writeFileSync(
    join(REPO_ROOT, "packages", "deployments", "src", "generated.ts"),
    deploymentsSource,
  );

  rmSync(PACKS_DIR, { recursive: true, force: true });
  mkdirSync(PACKS_DIR, { recursive: true });

  for (const name of PUBLISHABLE_PACKAGES) {
    const dir = join(REPO_ROOT, "packages", name);
    console.log(`[pack] @dotns/${name}: version`);
    await stampVersion(dir, version);
    console.log(`[pack] @dotns/${name}: build`);
    await buildPackage(dir);
    console.log(`[pack] @dotns/${name}: npm pack`);
    await packPackage(dir, PACKS_DIR);
  }

  console.log("[pack] done");
  for (const f of readdirSync(PACKS_DIR)) {
    console.log(`  ${join(PACKS_DIR, f)}`);
  }
}

await main();
