name = "dotns-resolver"
main = "src/limoResolver.ts"
compatibility_date = "2025-11-01"

[vars]
REGISTRY = "0xe2fB8d393D3A257F709A3a96d234950d00626fa5"
RESOLVER = "0x41df0d983C94ff742811649278faAa7fBfeb923D"
GATEWAY_URL = "https://ipfs.io/ipfs/"
RPC_URL = "https://testnet-passet-hub-eth-rpc.polkadot.io"

[[routes]]
pattern = "*.paseo-dotns.paritytech.io/*"
zone_name = "paritytech.io"
