// Regenerated by scripts/release/pack.ts before every release.

/** 20-byte EVM address in 0x-prefixed hex. */
export type Address = `0x${string}`;

/** A DotNS deployment on a single network: chain id, display name, and address book. */
export type Network = {
  chainId: number;
  name: string;
  addresses: Record<string, Address>;
};

/** Every network DotNS targets, keyed by friendly name. */
export const networks = {} as const satisfies Record<string, Network>;

/** Union of registered network keys. */
export type NetworkName = keyof typeof networks;
