name: Add Issues to DotNS Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          # Create a project at https://github.com/orgs/paritytech/projects/new
          # then paste the URL here, e.g. https://github.com/orgs/paritytech/projects/42
          project-url: ${{ vars.DOTNS_PROJECT_URL }}
          github-token: ${{ secrets.PROJECT_PAT }}
